Add arg support for docker-get-one

diff --git a/bin/docker-get-one b/bin/docker-get-one
--- a/bin/docker-get-one
+++ b/bin/docker-get-one
@@ -1,7 +1,14 @@
 #!/usr/bin/env bash
 
-if [[ $# == 0 ]]; then
-    exec docker ps --format '{{.Names}}' | head -1
-fi
+function get_container_name() {
+    if [[ $# == 0 ]]; then
+        docker ps --format '{{.Names}}' | head -1
+    else
+        docker ps --format '{{.Names}}' | grep -m1 "$*"
+    fi
+}
 
-exec docker ps --format '{{.Names}}' | grep -m1 "$*"
+if ! get_container_name "$@"; then
+    echo "Failed to get container name" >&2
+    exit 1
+fi
