Handle mac-term-dark-background osascript exit code

diff --git a/bin/mac-term-dark-background b/bin/mac-term-dark-background
--- a/bin/mac-term-dark-background
+++ b/bin/mac-term-dark-background
@@ -1,7 +1,11 @@
 #!/usr/bin/env bash
 
+set -e
 # Colors are in format "R, G, B" with each being a 16 bit sized integer, in decimal format
-mapfile -d',' -t background_color <<<"$(osascript -e 'tell application "Terminal" to get {background color} of window 1')"
+if ! output=$(osascript -e 'tell application "Terminal" to get {background color} of window 1'); then
+    exit 0  # Assume dark when command fails
+fi
+mapfile -d',' -t background_color <<<"$output"
 
 if [[ ${#background_color[@]} != 3 ]]; then
     echo "Failed to get terminal background color. Should be 3 items, was ${#background_color[@]}: ${background_color[*]}" >&2
